import childProcess from 'node:child_process'
import { globSync } from 'node:fs'
import { mkdir, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import shelljs from 'shelljs'

import { createApiApp } from '../../../builders/api.builder'
import { createMonorepoRoot } from '../../../builders/monorepo.builder'
import { apiParams, monorepoRootParams } from '../../helpers/fixtures'

const PROJECT = 'acme-ledger'
const DESCRIPTION = "Acme's ledger for regulated accounting"

/**
 * #884 — every generated API documented itself as "SaaSFoundryAI API", described as an
 * invoicing tool, with the CLI author's personal address as its contact: in its OpenAPI
 * configuration, in the document and Stoplight page it ships, and in the header of every
 * api-client file generated from that document.
 */
describe('the identity a generated API documents (#884)', () => {
  let tempDir: string
  let originalCwd: string
  let shellSpy: jest.SpyInstance
  let spawnSpy: jest.SpyInstance

  beforeAll(async () => {
    tempDir = join(tmpdir(), `sf-api-docs-identity-${Date.now()}`)
    originalCwd = process.cwd()
    await mkdir(join(tempDir, 'apps'), { recursive: true })
    process.chdir(tempDir)
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    shellSpy = jest.spyOn(shelljs, 'exec').mockImplementation((() => ({ code: 0, stdout: '10.0.0', stderr: '' })) as any)
    spawnSpy = jest.spyOn(childProcess, 'spawnSync').mockReturnValue({ status: 0, stdout: '', stderr: '' } as never)
    await createApiApp(apiParams({ isMonorepo: true, projectName: PROJECT, projectDescription: DESCRIPTION }))
    await createMonorepoRoot(monorepoRootParams({ projectName: PROJECT, projectDescription: DESCRIPTION }))
  }, 120_000)

  afterAll(async () => {
    shellSpy.mockRestore()
    spawnSpy.mockRestore()
    process.chdir(originalCwd)
    await rm(tempDir, { recursive: true, force: true }).catch(() => {})
  })

  const read = (path: string) => readFile(join(tempDir, path), 'utf8')

  it('configures the OpenAPI document with the project name and description, and no contact', async () => {
    const config = await read('apps/api/src/configs/api-docs/open-api.config.ts')

    expect(config).toContain(`title: '${PROJECT} API',`)
    // An apostrophe: double quotes, as the project's prettier prints it
    expect(config).toContain(`description: "${DESCRIPTION}",`)
    expect(config).not.toMatch(/contact:|SaaSFoundryAI|diamondforge|invoices/i)
  })

  it('no longer sets a contact, and titles the Stoplight page from the configuration', async () => {
    const service = await read('apps/api/src/modules/api-docs/services/api-docs.service.ts')

    expect(service).not.toContain('setContact')
    expect(service).toContain('<title>${openApiConfig.title} documentation</title>')
    expect(service).not.toContain('SaaSFoundryAI')
  })

  it('ships an OpenAPI document and an offline reference that name the project', async () => {
    const document = JSON.parse(await read('apps/api/docs/openapi.json')) as { info: Record<string, unknown> }

    expect(document.info).toEqual({ title: `${PROJECT} API`, description: DESCRIPTION, version: expect.any(String), license: expect.any(Object) })
    expect(await read('apps/api/docs/index.html')).toContain(`<title>${PROJECT} API documentation</title>`)
  })

  // The headers must agree with the document, or `npm run codegen:check` reports drift on the first commit
  it('heads every generated api-client file with the same title and description', async () => {
    const files = globSync('packages/api-client/src/generated/**/*.ts', { cwd: tempDir })
    const headed = []
    for (const file of files) {
      const source = await read(file)
      expect(source).not.toMatch(/SaaSFoundryAI|invoices/)
      if (source.includes('Generated by orval')) headed.push(source)
    }
    expect(headed.length).toBeGreaterThan(50)
    for (const source of headed) expect(source).toContain(` * ${PROJECT} API\n * ${DESCRIPTION}\n`)
  })

  it('labels its images without pointing at the template repository', async () => {
    for (const dockerfile of ['apps/api/Dockerfile']) expect(await read(dockerfile)).not.toMatch(/agachet|SaaSFoundryAI/)
  })
})
