import { constants } from 'fs'
import { chmod, link, lstat, mkdir, mkdtemp, open, readFile, rename, rm, symlink, writeFile } from 'fs/promises'
import { tmpdir } from 'os'
import { dirname, join } from 'path'

import { safeWriteAgentFile } from '../../../harness/agent-file-writer'

jest.mock('fs/promises', () => ({ ...jest.requireActual<typeof import('fs/promises')>('fs/promises') }))
const mockedFs = jest.requireMock<typeof import('fs/promises')>('fs/promises')

describe('safeWriteAgentFile', () => {
  let root: string
  let outside: string

  beforeEach(async () => {
    root = await mkdtemp(join(tmpdir(), 'sf-agent-writer-'))
    outside = await mkdtemp(join(tmpdir(), 'sf-agent-writer-outside-'))
  })

  afterEach(async () => {
    jest.restoreAllMocks()
    await Promise.all([rm(root, { recursive: true, force: true }), rm(outside, { recursive: true, force: true })])
  })

  const path = (relative: string) => join(root, relative)
  const put = async (relative: string, content: string) => {
    await mkdir(dirname(path(relative)), { recursive: true })
    await writeFile(path(relative), content)
  }

  it('creates regular files and truncates an approved long file when updating it with shorter bytes', async () => {
    await safeWriteAgentFile(root, 'nested/AGENTS.md', Buffer.from('first content'), 0o640)
    expect(await readFile(path('nested/AGENTS.md'), 'utf8')).toBe('first content')

    const expected = Buffer.from('a deliberately long generated instruction file')
    await writeFile(path('nested/AGENTS.md'), expected)
    await safeWriteAgentFile(root, 'nested/AGENTS.md', Buffer.from('short'), 0o640, expected)

    expect(await readFile(path('nested/AGENTS.md'))).toEqual(Buffer.from('short'))
    expect((await lstat(path('nested/AGENTS.md'))).size).toBe(5)
  })

  it('does not truncate a borrowed file whose expected bytes no longer match', async () => {
    await put('AGENTS.md', 'borrowed user instructions that must remain complete')
    const before = await readFile(path('AGENTS.md'))

    await expect(safeWriteAgentFile(root, 'AGENTS.md', Buffer.from('new'), 0o644, Buffer.from('older generated bytes'))).rejects.toThrow(/changed before writing/i)

    expect(await readFile(path('AGENTS.md'))).toEqual(before)
  })

  it('rejects final symlinks and hardlinks without changing the outside inode', async () => {
    const external = join(outside, 'instructions.md')
    await writeFile(external, 'outside content')
    await symlink(external, path('AGENTS.md'))

    await expect(safeWriteAgentFile(root, 'AGENTS.md', Buffer.from('replacement'), 0o644, Buffer.from('outside content'))).rejects.toThrow(/exclusive regular file/i)
    expect(await readFile(external, 'utf8')).toBe('outside content')

    await rm(path('AGENTS.md'))
    await link(external, path('AGENTS.md'))
    await expect(safeWriteAgentFile(root, 'AGENTS.md', Buffer.from('replacement'), 0o644, Buffer.from('outside content'))).rejects.toThrow(/exclusive regular file/i)
    expect(await readFile(external, 'utf8')).toBe('outside content')
  })

  it('does not follow a destination swapped to a symlink between lstat and open', async () => {
    await put('AGENTS.md', 'approved bytes')
    const external = join(outside, 'victim.md')
    await writeFile(external, 'outside content')
    const originalOpen = open
    jest.spyOn(mockedFs, 'open').mockImplementationOnce(async (destination, flags, mode) => {
      await rename(path('AGENTS.md'), path('AGENTS.approved.md'))
      await symlink(external, path('AGENTS.md'))
      return originalOpen(destination, flags, mode)
    })

    await expect(safeWriteAgentFile(root, 'AGENTS.md', Buffer.from('new bytes'), 0o644, Buffer.from('approved bytes'))).rejects.toBeDefined()

    expect(await readFile(external, 'utf8')).toBe('outside content')
    expect(await readFile(path('AGENTS.approved.md'), 'utf8')).toBe('approved bytes')
  })

  it('detects a parent symlink swap after opening and before writing any new bytes', async () => {
    await put('nested/AGENTS.md', 'approved bytes')
    const nested = path('nested')
    const parked = path('nested-original')
    const originalLstat = lstat
    let parentChecks = 0
    jest.spyOn(mockedFs, 'lstat').mockImplementation(async (target) => {
      if (String(target) === nested && ++parentChecks === 2) {
        await rename(nested, parked)
        await symlink(outside, nested)
      }
      return originalLstat(target)
    })

    await expect(safeWriteAgentFile(root, 'nested/AGENTS.md', Buffer.from('new bytes'), 0o644, Buffer.from('approved bytes'))).rejects.toThrow(/parent changed while opening/i)

    expect(await readFile(join(parked, 'AGENTS.md'), 'utf8')).toBe('approved bytes')
    await expect(readFile(join(outside, 'AGENTS.md'))).rejects.toMatchObject({ code: 'ENOENT' })
  })

  it('preserves an existing file mode and writes through a no-follow open handle', async () => {
    await put('AGENTS.md', 'old bytes')
    await chmod(path('AGENTS.md'), 0o600)
    let openedFlags = 0
    let handleWrite: jest.SpiedFunction<Awaited<ReturnType<typeof open>>['write']> | undefined
    const originalOpen = open
    jest.spyOn(mockedFs, 'open').mockImplementationOnce(async (destination, flags, mode) => {
      openedFlags = Number(flags)
      const handle = await originalOpen(destination, flags, mode)
      handleWrite = jest.spyOn(handle, 'write')
      return handle
    })

    await safeWriteAgentFile(root, 'AGENTS.md', Buffer.from('new bytes'), 0o777, Buffer.from('old bytes'))

    expect(openedFlags & constants.O_NOFOLLOW).toBe(constants.O_NOFOLLOW)
    expect(handleWrite).toHaveBeenCalled()
    expect((await lstat(path('AGENTS.md'))).mode & 0o777).toBe(0o600)
    expect(await readFile(path('AGENTS.md'), 'utf8')).toBe('new bytes')
  })
})
